-- begin POLICE_POLICE_STATION
alter table POLICE_POLICE_STATION add constraint FK_POLICE_STATION_ON_PROVINCE foreign key (PROVINCE_ID) references POLICE_PROVINCE(ID)^
alter table POLICE_POLICE_STATION add constraint FK_POLICE_STATION_ON_DISTRICT foreign key (DISTRICT_ID) references POLICE_DISTRICT(ID)^
create index IDX_POLICE_STATION_ON_PROVINCE on POLICE_POLICE_STATION (PROVINCE_ID)^
create index IDX_POLICE_STATION_ON_DISTRICT on POLICE_POLICE_STATION (DISTRICT_ID)^
-- end POLICE_POLICE_STATION
-- begin POLICE_OFFICER
alter table POLICE_OFFICER add constraint FK_POLICE_OFFICER_ON_RANK foreign key (RANK_ID) references POLICE_POLICE_RANK(ID)^
alter table POLICE_OFFICER add constraint FK_POLICE_OFFICER_ON_POLICE_STATION foreign key (POLICE_STATION_ID) references POLICE_POLICE_STATION(ID)^
create index IDX_POLICE_OFFICER_ON_RANK on POLICE_OFFICER (RANK_ID)^
create index IDX_POLICE_OFFICER_ON_POLICE_STATION on POLICE_OFFICER (POLICE_STATION_ID)^
-- end POLICE_OFFICER
-- begin POLICE_FINES
alter table POLICE_FINES add constraint FK_POLICE_FINES_ON_ISSUED_BY foreign key (ISSUED_BY_ID) references POLICE_OFFICER(ID)^
alter table POLICE_FINES add constraint FK_POLICE_FINES_ON_FINE_TYPE foreign key (FINE_TYPE_ID) references POLICE_FINE_TYPES(ID)^
alter table POLICE_FINES add constraint FK_POLICE_FINES_ON_POLICE_STATION foreign key (POLICE_STATION_ID) references POLICE_POLICE_STATION(ID)^
alter table POLICE_FINES add constraint FK_POLICE_FINES_ON_PROVINCE foreign key (PROVINCE_ID) references POLICE_PROVINCE(ID)^
alter table POLICE_FINES add constraint FK_POLICE_FINES_ON_DISTRICT foreign key (DISTRICT_ID) references POLICE_DISTRICT(ID)^
create index IDX_POLICE_FINES_ON_ISSUED_BY on POLICE_FINES (ISSUED_BY_ID)^
create index IDX_POLICE_FINES_ON_FINE_TYPE on POLICE_FINES (FINE_TYPE_ID)^
create index IDX_POLICE_FINES_ON_POLICE_STATION on POLICE_FINES (POLICE_STATION_ID)^
create index IDX_POLICE_FINES_ON_PROVINCE on POLICE_FINES (PROVINCE_ID)^
create index IDX_POLICE_FINES_ON_DISTRICT on POLICE_FINES (DISTRICT_ID)^
-- end POLICE_FINES
-- begin POLICE_FINE_SHEET
alter table POLICE_FINE_SHEET add constraint FK_POLICE_FINE_SHEET_ON_POLICE_STATION foreign key (POLICE_STATION_ID) references POLICE_POLICE_STATION(ID)^
alter table POLICE_FINE_SHEET add constraint FK_POLICE_FINE_SHEET_ON_ISSUED_TO foreign key (ISSUED_TO_ID) references POLICE_OFFICER(ID)^
alter table POLICE_FINE_SHEET add constraint FK_POLICE_FINE_SHEET_ON_ISSUED_BY foreign key (ISSUED_BY_ID) references POLICE_OFFICER(ID)^
create index IDX_POLICE_FINE_SHEET_ON_POLICE_STATION on POLICE_FINE_SHEET (POLICE_STATION_ID)^
create index IDX_POLICE_FINE_SHEET_ON_ISSUED_TO on POLICE_FINE_SHEET (ISSUED_TO_ID)^
create index IDX_POLICE_FINE_SHEET_ON_ISSUED_BY on POLICE_FINE_SHEET (ISSUED_BY_ID)^
-- end POLICE_FINE_SHEET
